### PR TITLE
Update fyne to 2.0.4

### PR DESCRIPTION
**Pull request by Jacalz**
This updates the fyne version to 2.0.4 from 2.0.2 which adds a lot of nice fixes and improvements :)

### CODE REVIEW

**Review by andydotxyz — CHANGES_REQUESTED** [review]
I think you forgot to run the `go mod vendor` command (and watch out for that GL file getting removed!)

**Comment by Jacalz** [comment]
> I think you forgot to run the `go mod vendor` command (and watch out for that GL file getting removed!)

Great catch. I think we need to update the PR template with that, just like we did in regular fyne :)

**Comment by Jacalz** [comment]
I got the vendor folder updated and added in that file as well (wasn't deleted here as it didn't exist here before) :)

**Review by andydotxyz — APPROVED** [review]

**Comment by andydotxyz** [comment]
> I got the vendor folder updated and added in that file as well (wasn't deleted here as it didn't exist here before) :)

Nice catch, thanks.

**Pull request merged**
