### PR TITLE
Clean up Makefile and check for destdir

### PR DESCRIPTION
**Pull request by Jacalz**
Also makes sure that binaries are ignored by git.

### CODE REVIEW

**Comment by andydotxyz** [comment]
Thanks for this, but you didn't describe why the fail message and return was removed - is that not a useful function?

**Comment by Jacalz** [comment]
Ah, right. Sorry. As make prints out each line before the executing it, I felt like it would be much clearer what went wrong. As an added benefit that the text that is printed out is more way to read and understand.

**Comment by andydotxyz** [comment]
Ah, so make will still exit early if we fail on one of those steps?

**Comment by Jacalz** [comment]
Good question. I hadn't thought about that part. Will check.

**Comment by Jacalz** [comment]
Looks like it indeed will do so.
image

**Review by andydotxyz — APPROVED** [review]

**Pull request merged**
