### PR TITLE
Spelling, grammar, and deference toward Oxford commas.

### PR DESCRIPTION
**Pull request by RocksteadyTC**
Jury's still out on the Oxford comma

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
@Jacalz Submitted for your approval

**Review by Jacalz — APPROVED** [review]
Just spelling mistakes. Don't know how much Oxford specifics it is. Thanks a lot :)

**Comment by RocksteadyTC** [comment]
🚀 alrighty folks, let's get this thing merged! What are we waiting on?

**Comment by andydotxyz** [comment]
Sorry, because we have moved to required hooks that are not on master yet (will be fixed on 0.3) it had to be an admin to merge.

**Pull request merged**
