### PR TITLE
Fix the bug of main menu display position when Runner is not used

### PR DESCRIPTION
**Pull request by myml**
Main menu can not show in embed mode. Position error due to height error.

### CODE REVIEW

**Comment by andydotxyz** [comment]
I'm not sure about this. You say the error is with embedded mode, but this code only runs when it's a full desktop...

**Comment by myml** [comment]
@andydotxyz  See https://github.com/fyne-io/fynedesk/blob/master/Makefile#L22

**Comment by andydotxyz** [comment]
Oh I see, that embed - apologies I did not understand.
But it works OK when running as a full desktop?

**Comment by myml** [comment]
> Oh I see, that embed - apologies I did not understand.
> But it works OK when running as a full desktop?

Yea! I have tested in X11 full desktop.

Befer: The main menu is located above the buttons, trigger mouse-leave event when menu is displayed, Then the menu is hidden.(The mouse must move quickly to the top after clicking)
Screenshot_deepin_2021-06-19_22:36:41
After: The main menu Normal display.
Screenshot_deepin_2021-06-19_22:37:32

**Comment by andydotxyz** [comment]
Ah I see, this relates to whether or not you are using fynedesk_runner.
With runner there is an additional menu item which is why it is normally taller.

**Comment by andydotxyz** [comment]
If you could update this to check:
```
	height := 124
	if os.Getenv("FYNE_DESK_RUNNER") != "" {
		height = 169
	}
```
then it should work in both instances.

**Comment by myml** [comment]
> If you could update this to check:
> 
> ```
> 	height := 136
> 	if os.Getenv("FYNE_DESK_RUNNER") != "" {
> 		height = 169
> 	}
> ```
> 
> then it should work in both instances.
> (note that in my testing 136 seemed to be the minimum height rather than 124)

You're right! I did not use runner, please see the latest code.

**Review by andydotxyz — CHANGES_REQUESTED** [review]
This looks great, but we keep functions in alphabetical order (grouped by type).
So could you please move `isRunner` up to above `max` (or rename it `usingRunner` as that is later in the alphabet ;) ).

**Comment by myml** [comment]
> This looks great, but we keep functions in alphabetical order (grouped by type).
> So could you please move `isRunner` up to above `max` (or rename it `usingRunner` as that is later in the alphabet ;) ).

It's simple.

**Comment by andydotxyz** [comment]
Sorry I did not notice before, it should be on the `develop` branch.
Also, for future PRs, please avoid force-pushing once a review has been added - it can make reviewing more difficult.

**Review by andydotxyz — APPROVED** [review]

**Comment by andydotxyz** [comment]
> Sorry I did not notice before, it should be on the `develop` branch.

I was able to rebase for you this time :)

**Pull request merged**
