### PR TITLE
Feature/appcache

### PR DESCRIPTION
**Pull request by andydotxyz**
Caching the app entries we find.
This was some development code that is really required for macOS as the lookup is so slow.
Should we add it to Linux/BSD code too? What should it's refresh strategy be?

### CODE REVIEW

**Comment by Jacalz** [comment]
Do we want to get this updated and rebased for landing in the next release? :slightly_smiling_face:

**Comment by andydotxyz** [comment]
I'll see if I can get it updated :)

**Comment by andydotxyz** [comment]
Happy to pick this up to land before release, what did you think might be sensible answers to the questions this PR posed @Jacalz ?

> Should we add it to Linux/BSD code too? What should it's refresh strategy be?

**Comment by Jacalz** [comment]
Hmm, 

> Happy to pick this up to land before release, what did you think might be sensible answers to the questions this PR posed @Jacalz ?
> 
> > Should we add it to Linux/BSD code too? What should it's refresh strategy be?

I think having it on Linux and BSD could be a good idea. As for the refresh strategy, just listening for file system notifications in `/usr/share/applications` might work, but feels like a hacky-ish solution. I'd go with something listening in on something like [update-desktop-database](https://manpages.ubuntu.com/manpages/cosmic/man1/update-desktop-database.1.html), if possible. I don't exactly know how Gnome and the others are doing this.

**Comment by AlbinoGeek** [comment]
Looks like they listen to filesystem updates on `$XDG_DATA_DIRS/applications/mimeinfo.cache`

I'm going to have to look into this and see what you guys did for the AppCache -- as I'd implemented this (Desktop entries + pulling extended information from supported software launchers such as Citrix, Origin, Steam, Uplay.) -- But ultimately ran into issues actually utilizing the data (the whole "Changing the image of a `Card` in a `GridWrap` = full second of lag refreshing the whole `GridWrap` / all `Card`s.")

**Comment by andydotxyz** [comment]
Merging to complete reload strategy on develop

**Pull request merged**
