### PR TITLE
Show battery level in the icon

### PR DESCRIPTION
**Pull request by andydotxyz**
As it says on the tin :)

### Checklist:

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

100%
battery_full

25%
image

### CODE REVIEW

**Comment by andydotxyz** [comment]
In case it's not super clear this is really helpful in the narrow-bar mode as the progress widget is not shown

**Comment by Jacalz** [comment]
Would it make sense to have the battery icon  rotated 90 degrees and have the percentage shown as text within it (at least for the minibar)?

**Comment by andydotxyz** [comment]
To make that work it would have to be a much larger icon, which will make it out-of-place with the others.
Or very small text.

**Comment by andydotxyz** [comment]
Is that thumbs up a "will approve" or "needs work" - not sure what the current status is sorry @Jacalz

**Comment by Jacalz** [comment]
Ah, sorry. I was in a hurry and just wanted to indicate that I think you were right.

**Comment by andydotxyz** [comment]
Ah I see thanks.
I'll leave it here in case someone is able to approve.

**Comment by andydotxyz** [comment]
Review period over

**Pull request merged**
