### PR TITLE
Update multiple roots to only control Primary with Fyne

### PR DESCRIPTION
**Pull request by andydotxyz**
This speeds up load and reconfigure.
Seems more stable for the screen configuration too.

### CODE REVIEW

**Review by okratitan — COMMENTED** [review]
This looks good and I am currently running this PR and it definitely feels snappy and seems to initially configure well.  However there are a ton of issues and crashes now when it comes to reconfiguring screens using something like arandr.  Resolutions go wackadoodle and can never get back to the original - clicking the widgets on the primary screens constantly crash after switching primary screen and coming back to the original. Scale is wackadoodle if primary screens are changed to a screen with different scale and back to the original etc...  So while the speed and initial configuring setup is really nice - this seems to have broke a lot of the niceties we had from multi root and scale and the work we had done on getting configuring screens right.  I'll dig some more and try to provide crash logs and point to problem areas in the code causing the issues, but for now I just wanted to point the issues I'm seeing.

**Comment by andydotxyz** [comment]
If you could provide more details that would really help.
I have tested here using a 4k laptop screen, a HiDPI monitor and a standard DPI screen.
Changing primary screens and altering user configured scale all seemed to work fine for me.
The crash info would be helpful - I have not seen any crashes and I use this branch constantly.

Can you please also provide more information about "broke a lot of the niceties we had from multi root" - what is broken?
Scale and window dragging etc all work perfectly here...

**Comment by andydotxyz** [comment]
@Jacalz you mentioned testing this branch before, but did not mention any issues - can you replicate any of what @okratitan reported?

**Comment by Jacalz** [comment]
@andydotxyz I did not see those issues, but both my screens are 1080p and I haven't messed about with `arandr` much.

**Comment by andydotxyz** [comment]
@okratitan it's been a week since your last comment - are there any logs or reproduction steps that you can provide to show exactly the issues you are facing?
I'm kindof stuck at this point, the main changes in this PR are now 3 weeks old and I don't feel any closer to getting it landed.

**Review by okratitan — APPROVED** [review]

**Review by Jacalz — APPROVED** [review]
Works much better than before for me. Approving :)

**Pull request merged**
